### ISSUE TITLE
Tracking down missing slides :) 

### ISSUE THREAD

**Issue by tanho63** [r4ds/bookclub-R_for_Data_Science#27]
Hi folks! I'm tagging some presenters that we don't yet have slides for in the repo - we'd love to have them so that others can refer back to them later!

- [ ] @nehamoopen for Ch4/5
- [ ] @shmuhammad2004 for Ch6/7 and Ch11
- [ ] @camcaan for Ch10

Let me know if there's anything I can do to help!
